task: 'simi_node_CL'
data:
#  datapath,batch_size,is_dir=False,num_workers=0
  batch_size: 16
  datapath: 'data/Aifb/all_data.pkl'
  num_workers: 0
model:
#  use_feature,feature_dim,d_model,type_num, L,neg_num,dropout,lr,wd
  aggregator: 'agat'
  use_feature: False
  feature_dim: 1156
  d_model: 32
  type_num: 4
  L: 3
  use_gradient_checkpointing: False
  lr: 0.01
  wd: 0.005
  dropout: 0.1
callback:
  monitor: 'micro-f1'
  mode: 'max'
train:
  max_epochs: 50
  gpus: 1
#  reload_dataloaders_every_n_epochs: 1
