data:
#  datapath,batch_size,is_dir=False,num_workers=0
  batch_size: 4096
  datapath: 'data/amazon/all_data.pkl'
  is_dir: False
  num_workers: 0
model:
#  use_feature,feature_dim,d_model,type_num, L,neg_num,dropout,lr,wd
  aggregator: 'agat'
  use_feature: True
  feature_dim: 1156
  d_model: 64
  type_num: 2
  L: 6
  use_gradient_checkpointing: False
  neg_num: 1
  lr: 0.005
  wd: 0.000
  dropout: 0.1
callback:
  monitor: 'val_auc'
  mode: 'max'
train:
  max_epochs: 200
  gpus: 1
#  reload_dataloaders_every_n_epochs: 1
