data:
#  datapath,batch_size,is_dir=False,num_workers=0
  batch_size: 4096
  datapath: 'data/amazon/all_data.pkl'
  is_dir: False
  num_workers: 0
model:
#  use_feature,feature_dim,d_model,type_num, L,neg_num,dropout,lr,wd
  use_feature: True
  feature_dim: 1156
  d_model: 32
  type_num: 2
  L: 3
  use_gradient_checkpointing: False
  neg_num: 5
  lr: 0.01
  wd: 0.0001
  dropout: 0.1
callback:
  monitor: 'val_auc'
  mode: 'max'
train:
  max_epochs: 100
  gpus: 1
#  reload_dataloaders_every_n_epochs: 1
#  resume_from_checkpoint: 'lightning_logs/version_0/checkpoints/epoch=96-step=6789.ckpt'
