task: 'simi_node_CL'
data:
  batch_size: 32
  datapath: 'data/PubMed/all_data.pkl'
  num_workers: 0
model:
  aggregator: 'agat'
  use_feature: True
  feature_dim: 200
  d_model: 64
  type_num: 8
  L: 3
  use_gradient_checkpointing: True
  lr: 0.005
  wd: 0.000
  dropout: 0.1
callback:
  monitor: 'micro-f1'
  mode: 'max'
train:
  max_epochs: 100
  gpus: 1
#  reload_dataloaders_every_n_epochs: 1
