task: 'link_rank'
data:
#  datapath,batch_size,is_dir=False,num_workers=0
  batch_size: 4096
  datapath: 'data/WN18RR/all_data.pkl'
  num_workers: 0
model:
#  use_feature,feature_dim,d_model,type_num, L,neg_num,dropout,lr,wd
  aggregator: 'agat'
  use_feature: False
  feature_dim: 1156
  d_model: 64
#  reverse
  type_num: 22
  neg_num: 10
  L: 3
  use_gradient_checkpointing: True
  lr: 0.005
  wd: 0.000
  dropout: 0.1
callback:
  monitor: 'mrr'
  mode: 'max'
train:
  max_epochs: 200
  gpus: 1
  precision: 16
